# Disable the "core" tomcat plugins
disablePlugins:
  - lando-tomcat

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/tomcat": /home/runner/work/tomcat/tomcat

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev
